name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Setup ESLint
        run: |
          npm install --save-dev eslint@7.23.0 eslint-config-airbnb@18.2.1 eslint-config-airbnb-base@14.2.1 eslint-plugin-import@2.28.1 eslint-plugin-jsx-a11y@6.7.1 eslint-plugin-react@7.33.1 eslint-plugin-react-hooks@4.6.0 @babel/core@7.23.0 @babel/eslint-parser@7.22.15 @babel/plugin-syntax-jsx@7.22.5 @babel/preset-react@7.22.15
          [ -f .eslintrc.json ] 
      - name: ESLint Report
        run: npx eslint "**/*.{js,jsx}"
  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@15.10.3 stylelint-config-standard@34.0.0 stylelint-config-standard-scss@11.0.0 
          [ -f .stylelintrc.json ]
      - name: Stylelint Report
        run: npx stylelint "**/*.scss*"
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi